# fly.toml file generated for nitterbot on 2022-12-23T23:31:36-05:00

app = "nitterbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true